### PR TITLE
mv sinon.js to allure_combine directory

### PR DESCRIPTION
**Pull request by kisscelia**
https://github.com/MihanEntalpo/allure-single-html-file/issues/13

### CODE REVIEW

**Comment by kisscelia** [comment]
Hi, @MihanEntalpo 
please review, thank you very much.

I test it locally.

It works well.

image

**Comment by MihanEntalpo** [comment]
Please, increase version in setup.py and in versions.md, so it would be possible to upload new version to pip after your pull is merged

**Comment by kisscelia** [comment]
> Please, increase version in setup.py and in versions.md, so it would be possible to upload new version to pip after your pull is merged

OK

**Comment by MihanEntalpo** [comment]
> OK

Already done by myself, and uploaded new version to pip

**Pull request merged**
