### PR TITLE
1st, add dest argument; 2nd, rm server.js and sinon-9.2.4.js in the source folder.

### PR DESCRIPTION
**Pull request by kisscelia**
1. add --dest argument, default is None. if not provided, dest == source folder
2. rm server.js and sinon-9.2.4.js in the allure report source folder.

### CODE REVIEW

**Comment by kisscelia** [comment]
solve https://github.com/MihanEntalpo/allure-single-html-file/issues/8

**Comment by kisscelia** [comment]
Hi, @MihanEntalpo 
can you merge it?

Thank you. Expected.

**Review by MihanEntalpo — CHANGES_REQUESTED** [review]
Thanks for contribution!
1. In my use-case, files sinon.js and server.js are not temporary, they are used to open modified index.html. So, it'll be good to have additional command line argument like --remove-temp-files responsible for deletion of that files
2. Automatic creation of folder if it not exists (the specified one) is unintuitive behaviour. I can't remember unix-like program, there you specify a folder to put file into, and its silently creating it with all parent folders. So, would you kindly add another command line argument, like --auto-create-folders or so

**Comment by kisscelia** [comment]
Hi, @MihanEntalpo 

> good to have additional command line argument like --remove-temp-files responsible for deletion of that files

agree. when command running finished. sinon.js and server.js will be useless. I will be add another argument. thanks for your advice.

> So, would you kindly add another command line argument, like --auto-create-folders or so

agree, i will do that. :)

**Comment by kisscelia** [comment]
> Thanks for contribution!
> 
> 1. In my use-case, files sinon.js and server.js are not temporary, they are used to open modified index.html. So, it'll be good to have additional command line argument like --remove-temp-files responsible for deletion of that files
> 2. Automatic creation of folder if it not exists (the specified one) is unintuitive behaviour. I can't remember unix-like program, there you specify a folder to put file into, and its silently creating it with all parent folders. So, would you kindly add another command line argument, like --auto-create-folders or so

Hi, @MihanEntalpo 
done, please review, thanks.

**Review by MihanEntalpo — APPROVED** [review]

**Review by MihanEntalpo — CHANGES_REQUESTED** [review]
Everything is ok now, except initialisation and usage of argparse, it should be in __main__ block of code, or in a separate function, called from __main__, because this script could be imported, not executed as console script, so argparse is bot needed in the root scope

**Comment by kisscelia** [comment]
> Everything is ok now, except initialisation and usage of argparse, it should be in **main** block of code, or in a separate function, called from **main**, because this script could be imported, not executed as console script, so argparse is bot needed in the root scope

Yes, you are right.

I will change it.

**Pull request merged**
